/** Códigos de error estables del contrato de la API (campo `errorCode`). */
export enum AuthErrorCode {
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  ACCOUNT_BLOCKED = 'AUTH_ACCOUNT_BLOCKED',
  EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
}
