/**
 * Códigos de error estables del contrato de API. El front reacciona a estos
 * (no al `message`). Se exponen en el envelope de error como `errorCode`.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  AUTH_ACCOUNT_BLOCKED = 'AUTH_ACCOUNT_BLOCKED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  AUTH_INVALID_RESET_TOKEN = 'AUTH_INVALID_RESET_TOKEN',
  AUTH_PASSWORD_MISMATCH = 'AUTH_PASSWORD_MISMATCH',
  AUTH_INVALID_VERIFICATION_TOKEN = 'AUTH_INVALID_VERIFICATION_TOKEN',
  AUTH_EMAIL_ALREADY_VERIFIED = 'AUTH_EMAIL_ALREADY_VERIFIED',
  // RBAC
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS',
  ROLE_IMMUTABLE = 'ROLE_IMMUTABLE',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  // Registro (M5)
  REGISTER_INVALID_ACCOUNT_TYPE = 'REGISTER_INVALID_ACCOUNT_TYPE',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  COMPANY_RFC_ALREADY_EXISTS = 'COMPANY_RFC_ALREADY_EXISTS',
  CANDIDATE_DOCUMENT_ALREADY_EXISTS = 'CANDIDATE_DOCUMENT_ALREADY_EXISTS',
  INVALID_BIRTH_DATE = 'INVALID_BIRTH_DATE',
  // Perfil candidato (M6)
  CANDIDATE_PROFILE_NOT_FOUND = 'CANDIDATE_PROFILE_NOT_FOUND',
  CANDIDATE_RESOURCE_NOT_FOUND = 'CANDIDATE_RESOURCE_NOT_FOUND',
  CANDIDATE_INVALID_DATE_RANGE = 'CANDIDATE_INVALID_DATE_RANGE',
  CANDIDATE_DATE_IN_FUTURE = 'CANDIDATE_DATE_IN_FUTURE',
  CANDIDATE_LANGUAGE_DUPLICATED = 'CANDIDATE_LANGUAGE_DUPLICATED',
  CANDIDATE_LANGUAGE_NOT_FOUND = 'CANDIDATE_LANGUAGE_NOT_FOUND',
  CANDIDATE_NATIVE_LEVEL_REQUIRED = 'CANDIDATE_NATIVE_LEVEL_REQUIRED',
}
